import { useState } from 'react';
import { Layout } from '@/components/Layout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useAuth } from '@/contexts/AuthContext';
import { getAttendance, getStaffList, getJobAllotments, type AttendanceRecord } from '@/lib/storage';
import { Download, FileText } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export default function Reports() {
  const { user } = useAuth();
  const [reportType, setReportType] = useState<'date' | 'driver'>('date');
  const [dateFrom, setDateFrom] = useState(new Date().toISOString().split('T')[0]);
  const [dateTo, setDateTo] = useState(new Date().toISOString().split('T')[0]);
  const [driverSearch, setDriverSearch] = useState('');
  const [selectedDriver, setSelectedDriver] = useState('');
  const [format, setFormat] = useState<'pdf' | 'excel'>('pdf');

  const staffList = getStaffList();
  const allAttendance = getAttendance();
  const allJobs = getJobAllotments();
  const filtered = staffList.filter(s => s.name.toLowerCase().includes(driverSearch.toLowerCase()));

  const getDriverStats = (staffId: string) => {
    const records = allAttendance.filter(r => r.staffId === staffId);
    return {
      present: records.filter(r => ['present', 'dcd', 'dcn'].includes(r.status)).length,
      absent: records.filter(r => r.status === 'absent').length,
      extraDuty: records.filter(r => r.status === 'extra_duty').length,
    };
  };

  const downloadDateReport = () => {
    const records = allAttendance.filter(r => r.date >= dateFrom && r.date <= dateTo);
    const isSingleDay = dateFrom === dateTo;

    if (format === 'pdf') {
      const doc = new jsPDF();
      doc.setFontSize(16);
      doc.text('SKL - Attendance Report', 14, 15);
      doc.setFontSize(10);
      doc.text(`Period: ${dateFrom} to ${dateTo} | Generated by: ${user?.displayName}`, 14, 24);

      const head = isSingleDay
        ? [['#', 'Driver Name', 'Mobile', 'Vehicle', 'Status']]
        : [['#', 'Driver Name', 'Mobile', 'Present', 'Absent', 'Extra Duty']];

      if (isSingleDay) {
        const body = records.map((r, i) => {
          const job = allJobs.find(j => j.date === r.date && j.shift === r.shift && j.staffId === r.staffId);
          const st = r.status === 'absent' ? 'A' : r.status === 'extra_duty' ? 'ED' : r.status === 'dcd' ? 'DCD' : r.status === 'dcn' ? 'DCN' : 'P';
          return [i + 1, r.staffName, r.mobile, job?.vehicleNumber || '-', st];
        });
        autoTable(doc, { startY: 30, head, body });
      } else {
        const driverMap = new Map<string, { name: string; mobile: string; present: number; absent: number; ed: number }>();
        records.forEach(r => {
          const existing = driverMap.get(r.staffId) || { name: r.staffName, mobile: r.mobile, present: 0, absent: 0, ed: 0 };
          if (['present', 'dcd', 'dcn'].includes(r.status)) existing.present++;
          else if (r.status === 'absent') existing.absent++;
          else if (r.status === 'extra_duty') existing.ed++;
          driverMap.set(r.staffId, existing);
        });
        const body = Array.from(driverMap.values()).map((d, i) => [i + 1, d.name, d.mobile, d.present, d.absent, d.ed]);
        autoTable(doc, { startY: 30, head, body });
      }
      doc.save(`report_${dateFrom}_${dateTo}.pdf`);
    } else {
      // Excel
      const records2 = allAttendance.filter(r => r.date >= dateFrom && r.date <= dateTo);
      if (isSingleDay) {
        const data = records2.map((r, i) => {
          const job = allJobs.find(j => j.date === r.date && j.shift === r.shift && j.staffId === r.staffId);
          const st = r.status === 'absent' ? 'A' : r.status === 'extra_duty' ? 'ED' : r.status === 'dcd' ? 'DCD' : r.status === 'dcn' ? 'DCN' : 'P';
          return { '#': i + 1, 'Driver Name': r.staffName, 'Mobile': r.mobile, 'Vehicle': job?.vehicleNumber || '-', 'Status': st };
        });
        const ws = XLSX.utils.json_to_sheet(data);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report');
        XLSX.writeFile(wb, `report_${dateFrom}.xlsx`);
      } else {
        const driverMap = new Map<string, any>();
        records2.forEach(r => {
          const existing = driverMap.get(r.staffId) || { 'Driver Name': r.staffName, 'Mobile': r.mobile, 'Present': 0, 'Absent': 0, 'Extra Duty': 0 };
          if (['present', 'dcd', 'dcn'].includes(r.status)) existing['Present']++;
          else if (r.status === 'absent') existing['Absent']++;
          else if (r.status === 'extra_duty') existing['Extra Duty']++;
          driverMap.set(r.staffId, existing);
        });
        const data = Array.from(driverMap.values()).map((d, i) => ({ '#': i + 1, ...d }));
        const ws = XLSX.utils.json_to_sheet(data);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Report');
        XLSX.writeFile(wb, `report_${dateFrom}_${dateTo}.xlsx`);
      }
    }
  };

  const downloadDriverReport = () => {
    if (!selectedDriver) return;
    const staff = staffList.find(s => s.id === selectedDriver);
    if (!staff) return;
    const records = allAttendance.filter(r => r.staffId === selectedDriver);
    const stats = getDriverStats(selectedDriver);

    if (format === 'pdf') {
      const doc = new jsPDF();
      doc.setFontSize(16);
      doc.text('SKL - Driver Report', 14, 15);
      doc.setFontSize(10);
      doc.text(`Driver: ${staff.name} | Mobile: ${staff.mobile} | Generated by: ${user?.displayName}`, 14, 24);
      doc.text(`Present: ${stats.present} | Absent: ${stats.absent} | Extra Duty: ${stats.extraDuty}`, 14, 32);
      autoTable(doc, {
        startY: 38,
        head: [['#', 'Date', 'Shift', 'Status']],
        body: records.map((r, i) => {
          const st = r.status === 'absent' ? 'A' : r.status === 'extra_duty' ? 'ED' : r.status === 'dcd' ? 'DCD' : r.status === 'dcn' ? 'DCN' : 'P';
          return [i + 1, r.date, r.shift.toUpperCase(), st];
        }),
      });
      doc.save(`driver_report_${staff.name}.pdf`);
    } else {
      const data = records.map((r, i) => ({
        '#': i + 1, Date: r.date, Shift: r.shift.toUpperCase(),
        Status: r.status === 'absent' ? 'A' : r.status === 'extra_duty' ? 'ED' : r.status.toUpperCase()
      }));
      const ws = XLSX.utils.json_to_sheet(data);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, 'Report');
      XLSX.writeFile(wb, `driver_report_${staff.name}.xlsx`);
    }
  };

  const selectedStats = selectedDriver ? getDriverStats(selectedDriver) : null;

  return (
    <Layout>
      <div className="space-y-6 max-w-4xl mx-auto">
        <h2 className="text-2xl font-bold">Reports</h2>

        <div className="flex gap-2">
          <Button variant={reportType === 'date' ? 'default' : 'outline'} onClick={() => setReportType('date')}>Date Wise</Button>
          <Button variant={reportType === 'driver' ? 'default' : 'outline'} onClick={() => setReportType('driver')}>Driver Wise</Button>
        </div>

        {reportType === 'date' ? (
          <Card>
            <CardHeader><CardTitle>Date Wise Report</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="space-y-2"><Label>From</Label><Input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} /></div>
                <div className="space-y-2"><Label>To</Label><Input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} /></div>
                <div className="space-y-2">
                  <Label>Format</Label>
                  <Select value={format} onValueChange={v => setFormat(v as 'pdf' | 'excel')}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="pdf">PDF</SelectItem>
                      <SelectItem value="excel">Excel</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <Button onClick={downloadDateReport}><Download className="h-4 w-4 mr-1" />Download Report</Button>
            </CardContent>
          </Card>
        ) : (
          <Card>
            <CardHeader><CardTitle>Driver Wise Report</CardTitle></CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Driver Name</Label>
                  <Input placeholder="Type to search..." value={driverSearch}
                    onChange={e => { setDriverSearch(e.target.value); setSelectedDriver(''); }} />
                  {driverSearch && !selectedDriver && (
                    <div className="border rounded-md max-h-40 overflow-auto bg-popover">
                      {filtered.map(s => (
                        <div key={s.id} className="px-3 py-2 hover:bg-muted cursor-pointer text-sm"
                          onClick={() => { setSelectedDriver(s.id); setDriverSearch(s.name); }}>{s.name}</div>
                      ))}
                    </div>
                  )}
                </div>
                <div className="space-y-2">
                  <Label>Format</Label>
                  <Select value={format} onValueChange={v => setFormat(v as 'pdf' | 'excel')}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="pdf">PDF</SelectItem>
                      <SelectItem value="excel">Excel</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              {selectedStats && (
                <div className="flex gap-4 text-sm">
                  <span className="text-success font-medium">Present: {selectedStats.present}</span>
                  <span className="text-destructive font-medium">Absent: {selectedStats.absent}</span>
                  <span className="text-warning font-medium">Extra Duty: {selectedStats.extraDuty}</span>
                </div>
              )}
              <Button onClick={downloadDriverReport} disabled={!selectedDriver}><Download className="h-4 w-4 mr-1" />Download Report</Button>
            </CardContent>
          </Card>
        )}
      </div>
    </Layout>
  );
}
